name: Upload IRCC Forecast to Firestore

on:
  workflow_dispatch:  # Allow manual trigger from GitHub UI
  schedule:
    - cron: '0 10 * * *'  # Runs every Monday 9AM EST (13:00 UTC)

jobs:
  update-forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install firebase-admin requests

      - name: Run forecast script
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        run: |
          python scripts/forecast_to_firestore.py
